/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Oct  6 15:57:55 2025


#include "YarpLoggerRerun_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(YarpLoggerRerunParamsCOMPONENT, "yarp.device.YarpLoggerRerun")
}


YarpLoggerRerun_ParamsParser::YarpLoggerRerun_ParamsParser()
{
}


std::vector<std::string> YarpLoggerRerun_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("robot");
    params.push_back("remote");
    params.push_back("urdf");
    params.push_back("viewer_ip");
    params.push_back("saveToFile");
    params.push_back("logIEncoders");
    return params;
}


bool YarpLoggerRerun_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="robot")
    {
        paramValue = m_robot;
        return true;
    }
    if (paramName =="remote")
    {
        paramValue = m_remote;
        return true;
    }
    if (paramName =="urdf")
    {
        paramValue = m_urdf;
        return true;
    }
    if (paramName =="viewer_ip")
    {
        paramValue = m_viewer_ip;
        return true;
    }
    if (paramName =="saveToFile")
    {
        if (m_saveToFile==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="logIEncoders")
    {
        if (m_logIEncoders==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string YarpLoggerRerun_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      YarpLoggerRerun_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(YarpLoggerRerunParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter robot
    {
        if (config.check("robot"))
        {
            m_robot = config.find("robot").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'robot' using value:" << m_robot;
        }
        else
        {
            yCError(YarpLoggerRerunParamsCOMPONENT) << "Mandatory parameter 'robot' not found!";
            yCError(YarpLoggerRerunParamsCOMPONENT) << "Description of the parameter: Name of the robot";
            return false;
        }
        prop_check.unput("robot");
    }

    //Parser of parameter remote
    {
        if (config.check("remote"))
        {
            m_remote = config.find("remote").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'remote' using value:" << m_remote;
        }
        else
        {
            yCError(YarpLoggerRerunParamsCOMPONENT) << "Mandatory parameter 'remote' not found!";
            yCError(YarpLoggerRerunParamsCOMPONENT) << "Description of the parameter: Name of the port to attach to";
            return false;
        }
        prop_check.unput("remote");
    }

    //Parser of parameter urdf
    {
        if (config.check("urdf"))
        {
            m_urdf = config.find("urdf").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'urdf' using value:" << m_urdf;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'urdf' using DEFAULT value:" << m_urdf;
        }
        prop_check.unput("urdf");
    }

    //Parser of parameter viewer_ip
    {
        if (config.check("viewer_ip"))
        {
            m_viewer_ip = config.find("viewer_ip").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'viewer_ip' using value:" << m_viewer_ip;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'viewer_ip' using DEFAULT value:" << m_viewer_ip;
        }
        prop_check.unput("viewer_ip");
    }

    //Parser of parameter saveToFile
    {
        if (config.check("saveToFile"))
        {
            m_saveToFile = config.find("saveToFile").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'saveToFile' using value:" << m_saveToFile;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'saveToFile' using DEFAULT value:" << m_saveToFile;
        }
        prop_check.unput("saveToFile");
    }

    //Parser of parameter logIEncoders
    {
        if (config.check("logIEncoders"))
        {
            m_logIEncoders = config.find("logIEncoders").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIEncoders' using value:" << m_logIEncoders;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIEncoders' using DEFAULT value:" << m_logIEncoders;
        }
        prop_check.unput("logIEncoders");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(YarpLoggerRerunParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(YarpLoggerRerunParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      YarpLoggerRerun_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: YarpLoggerRerun\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'robot': Name of the robot\n");
    doc = doc + std::string("'remote': Name of the port to attach to\n");
    doc = doc + std::string("'urdf': \n");
    doc = doc + std::string("'viewer_ip': \n");
    doc = doc + std::string("'saveToFile': \n");
    doc = doc + std::string("'logIEncoders': \n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device yarpLoggerRerun --robot <mandatory_value> --remote <mandatory_value> --urdf model.urdf --viewer_ip localhost --saveToFile false --logIEncoders true\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device yarpLoggerRerun --robot <mandatory_value> --remote <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
