/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Oct 17 12:07:59 2025


#ifndef YARPLOGGERRERUN_PARAMSPARSER_H
#define YARPLOGGERRERUN_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class YarpLoggerRerun.
*
* These are the used parameters:
* | Group name | Parameter name | Type           | Units | Default Value | Required | Description | Notes |
* |:----------:|:--------------:|:--------------:|:-----:|:-------------:|:--------:|:-----------:|:-----:|
* | -          | axesNames      | vector<string> | -     | -             | 1        | -           | -     |
* | -          | logIEncoders   | bool           | -     | -             | 1        | -           | -     |
* | -          | logURDF        | bool           | -     | -             | 1        | -           | -     |
* | -          | fileName       | string         | -     | -             | 1        | -           | -     |
* | -          | filePath       | string         | -     | -             | 1        | -           | -     |
* | -          | saveToFile     | bool           | -     | -             | 1        | -           | -     |
* | -          | viewerIp       | string         | -     | -             | 1        | -           | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun --axesNames <mandatory_value> --logIEncoders <mandatory_value> --logURDF <mandatory_value> --fileName <mandatory_value> --filePath <mandatory_value> --saveToFile <mandatory_value> --viewerIp <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun --axesNames <mandatory_value> --logIEncoders <mandatory_value> --logURDF <mandatory_value> --fileName <mandatory_value> --filePath <mandatory_value> --saveToFile <mandatory_value> --viewerIp <mandatory_value>
* \endcode
*
*/

class YarpLoggerRerun_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    YarpLoggerRerun_ParamsParser();
    ~YarpLoggerRerun_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"YarpLoggerRerun"};
    const std::string m_device_name = {"yarpLoggerRerun"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_axesNames_defaultValue = {""};
    const std::string m_logIEncoders_defaultValue = {""};
    const std::string m_logURDF_defaultValue = {""};
    const std::string m_fileName_defaultValue = {""};
    const std::string m_filePath_defaultValue = {""};
    const std::string m_saveToFile_defaultValue = {""};
    const std::string m_viewerIp_defaultValue = {""};

    std::vector<std::string> m_axesNames = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    bool m_logIEncoders = {false}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    bool m_logURDF = {false}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_fileName = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_filePath = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    bool m_saveToFile = {false}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_viewerIp = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
