/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Oct 15 09:39:42 2025


#ifndef YARPLOGGERRERUN_PARAMSPARSER_H
#define YARPLOGGERRERUN_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class YarpLoggerRerun.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                   | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:-----------------------------:|:-----:|
* | -          | robot          | string | -     | -             | 0        | Name of the robot             | -     |
* | -          | remote         | string | -     | -             | 0        | Name of the port to attach to | -     |
* | -          | urdf           | string | -     | model.urdf    | 0        | -                             | -     |
* | -          | viewer_ip      | string | -     | localhost     | 0        | -                             | -     |
* | -          | saveToFile     | bool   | -     | false         | 0        | -                             | -     |
* | -          | logIEncoders   | bool   | -     | true          | 0        | -                             | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun --robot <optional_value> --remote <optional_value> --urdf model.urdf --viewer_ip localhost --saveToFile false --logIEncoders true
* \endcode
*
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun
* \endcode
*
*/

class YarpLoggerRerun_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    YarpLoggerRerun_ParamsParser();
    ~YarpLoggerRerun_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"YarpLoggerRerun"};
    const std::string m_device_name = {"yarpLoggerRerun"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_robot_defaultValue = {""};
    const std::string m_remote_defaultValue = {""};
    const std::string m_urdf_defaultValue = {"model.urdf"};
    const std::string m_viewer_ip_defaultValue = {"localhost"};
    const std::string m_saveToFile_defaultValue = {"false"};
    const std::string m_logIEncoders_defaultValue = {"true"};

    std::string m_robot = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    std::string m_remote = {}; //This default value of this string is an empty string. It is highly recommended to provide a suggested value also for optional string parameters.
    std::string m_urdf = {"model.urdf"};
    std::string m_viewer_ip = {"localhost"};
    bool m_saveToFile = {false};
    bool m_logIEncoders = {true};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
