/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Oct 20 10:23:56 2025


#include "YarpLoggerRerun_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(YarpLoggerRerunParamsCOMPONENT, "yarp.device.YarpLoggerRerun")
}


YarpLoggerRerun_ParamsParser::YarpLoggerRerun_ParamsParser()
{
}


std::vector<std::string> YarpLoggerRerun_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("axesNames");
    params.push_back("logIEncoders");
    params.push_back("logIMotorEncoders");
    params.push_back("logIPidControl");
    params.push_back("logURDF");
    params.push_back("fileName");
    params.push_back("filePath");
    params.push_back("saveToFile");
    params.push_back("viewerIp");
    return params;
}


bool YarpLoggerRerun_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="axesNames")
    {
        return false;
    }
    if (paramName =="logIEncoders")
    {
        if (m_logIEncoders==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="logIMotorEncoders")
    {
        if (m_logIMotorEncoders==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="logIPidControl")
    {
        if (m_logIPidControl==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="logURDF")
    {
        if (m_logURDF==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="fileName")
    {
        paramValue = m_fileName;
        return true;
    }
    if (paramName =="filePath")
    {
        paramValue = m_filePath;
        return true;
    }
    if (paramName =="saveToFile")
    {
        if (m_saveToFile==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="viewerIp")
    {
        paramValue = m_viewerIp;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string YarpLoggerRerun_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      YarpLoggerRerun_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(YarpLoggerRerunParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter axesNames
    {
        if (config.check("axesNames"))
        {
            {
                m_axesNames.clear();
                yarp::os::Bottle* tempBot = config.find("axesNames").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_axesNames.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(YarpLoggerRerunParamsCOMPONENT) <<"parameter 'axesNames' is not a properly formatted bottle";
                }
            }
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'axesNames' using value:" << m_axesNames;
        }
        else
        {
            yCError(YarpLoggerRerunParamsCOMPONENT) << "Mandatory parameter 'axesNames' not found!";
            return false;
        }
        prop_check.unput("axesNames");
    }

    //Parser of parameter logIEncoders
    {
        if (config.check("logIEncoders"))
        {
            m_logIEncoders = config.find("logIEncoders").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIEncoders' using value:" << m_logIEncoders;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIEncoders' using DEFAULT value:" << m_logIEncoders;
        }
        prop_check.unput("logIEncoders");
    }

    //Parser of parameter logIMotorEncoders
    {
        if (config.check("logIMotorEncoders"))
        {
            m_logIMotorEncoders = config.find("logIMotorEncoders").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIMotorEncoders' using value:" << m_logIMotorEncoders;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIMotorEncoders' using DEFAULT value:" << m_logIMotorEncoders;
        }
        prop_check.unput("logIMotorEncoders");
    }

    //Parser of parameter logIPidControl
    {
        if (config.check("logIPidControl"))
        {
            m_logIPidControl = config.find("logIPidControl").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIPidControl' using value:" << m_logIPidControl;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logIPidControl' using DEFAULT value:" << m_logIPidControl;
        }
        prop_check.unput("logIPidControl");
    }

    //Parser of parameter logURDF
    {
        if (config.check("logURDF"))
        {
            m_logURDF = config.find("logURDF").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logURDF' using value:" << m_logURDF;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'logURDF' using DEFAULT value:" << m_logURDF;
        }
        prop_check.unput("logURDF");
    }

    //Parser of parameter fileName
    {
        if (config.check("fileName"))
        {
            m_fileName = config.find("fileName").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'fileName' using value:" << m_fileName;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'fileName' using DEFAULT value:" << m_fileName;
        }
        prop_check.unput("fileName");
    }

    //Parser of parameter filePath
    {
        if (config.check("filePath"))
        {
            m_filePath = config.find("filePath").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'filePath' using value:" << m_filePath;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'filePath' using DEFAULT value:" << m_filePath;
        }
        prop_check.unput("filePath");
    }

    //Parser of parameter saveToFile
    {
        if (config.check("saveToFile"))
        {
            m_saveToFile = config.find("saveToFile").asBool();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'saveToFile' using value:" << m_saveToFile;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'saveToFile' using DEFAULT value:" << m_saveToFile;
        }
        prop_check.unput("saveToFile");
    }

    //Parser of parameter viewerIp
    {
        if (config.check("viewerIp"))
        {
            m_viewerIp = config.find("viewerIp").asString();
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'viewerIp' using value:" << m_viewerIp;
        }
        else
        {
            yCInfo(YarpLoggerRerunParamsCOMPONENT) << "Parameter 'viewerIp' using DEFAULT value:" << m_viewerIp;
        }
        prop_check.unput("viewerIp");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(YarpLoggerRerunParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(YarpLoggerRerunParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      YarpLoggerRerun_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: YarpLoggerRerun\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'axesNames': \n");
    doc = doc + std::string("'logIEncoders': \n");
    doc = doc + std::string("'logIMotorEncoders': \n");
    doc = doc + std::string("'logIPidControl': \n");
    doc = doc + std::string("'logURDF': \n");
    doc = doc + std::string("'fileName': \n");
    doc = doc + std::string("'filePath': \n");
    doc = doc + std::string("'saveToFile': \n");
    doc = doc + std::string("'viewerIp': \n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device yarpLoggerRerun --axesNames <mandatory_value> --logIEncoders true --logIMotorEncoders false --logIPidControl false --logURDF false --fileName log_test --filePath /home/ergocub/test --saveToFile false --viewerIp localhost\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device yarpLoggerRerun --axesNames <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
