/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Nov 17 09:16:50 2025


#ifndef YARPLOGGERRERUN_PARAMSPARSER_H
#define YARPLOGGERRERUN_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class YarpLoggerRerun.
*
* These are the used parameters:
* | Group name | Parameter name       | Type           | Units | Default Value      | Required | Description | Notes |
* |:----------:|:--------------------:|:--------------:|:-----:|:------------------:|:--------:|:-----------:|:-----:|
* | -          | axesNames            | vector<string> | -     | -                  | 1        | -           | -     |
* | -          | logIEncoders         | bool           | -     | true               | 0        | -           | -     |
* | -          | logIMotorEncoders    | bool           | -     | false              | 0        | -           | -     |
* | -          | logIPidControl       | bool           | -     | false              | 0        | -           | -     |
* | -          | logITorqueControl    | bool           | -     | false              | 0        | -           | -     |
* | -          | logIAmplifierControl | bool           | -     | false              | 0        | -           | -     |
* | -          | logIControlMode      | bool           | -     | false              | 0        | -           | -     |
* | -          | logURDF              | bool           | -     | false              | 0        | -           | -     |
* | -          | fileName             | string         | -     | log_test           | 0        | -           | -     |
* | -          | filePath             | string         | -     | /home/ergocub/test | 0        | -           | -     |
* | -          | saveToFile           | bool           | -     | false              | 0        | -           | -     |
* | -          | viewerIp             | string         | -     | localhost          | 0        | -           | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun --axesNames <mandatory_value> --logIEncoders true --logIMotorEncoders false --logIPidControl false --logITorqueControl false --logIAmplifierControl false --logIControlMode false --logURDF false --fileName log_test --filePath /home/ergocub/test --saveToFile false --viewerIp localhost
* \endcode
*
* \code{.unparsed}
* yarpdev --device yarpLoggerRerun --axesNames <mandatory_value>
* \endcode
*
*/

class YarpLoggerRerun_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    YarpLoggerRerun_ParamsParser();
    ~YarpLoggerRerun_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"YarpLoggerRerun"};
    const std::string m_device_name = {"yarpLoggerRerun"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_axesNames_defaultValue = {""};
    const std::string m_logIEncoders_defaultValue = {"true"};
    const std::string m_logIMotorEncoders_defaultValue = {"false"};
    const std::string m_logIPidControl_defaultValue = {"false"};
    const std::string m_logITorqueControl_defaultValue = {"false"};
    const std::string m_logIAmplifierControl_defaultValue = {"false"};
    const std::string m_logIControlMode_defaultValue = {"false"};
    const std::string m_logURDF_defaultValue = {"false"};
    const std::string m_fileName_defaultValue = {"log_test"};
    const std::string m_filePath_defaultValue = {"/home/ergocub/test"};
    const std::string m_saveToFile_defaultValue = {"false"};
    const std::string m_viewerIp_defaultValue = {"localhost"};

    std::vector<std::string> m_axesNames = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    bool m_logIEncoders = {true};
    bool m_logIMotorEncoders = {false};
    bool m_logIPidControl = {false};
    bool m_logITorqueControl = {false};
    bool m_logIAmplifierControl = {false};
    bool m_logIControlMode = {false};
    bool m_logURDF = {false};
    std::string m_fileName = {"log_test"};
    std::string m_filePath = {"/home/ergocub/test"};
    bool m_saveToFile = {false};
    std::string m_viewerIp = {"localhost"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
